### ISSUE TITLE
Enhancement: Decide on how to go up to the next level (animation, falling etc.)

### ISSUE THREAD

**Issue by whitew1994WW** [kepler471/moonshot#178]
- Decide on how we are going up to the next level
- Change the existing code so that this works
- Create sprite
- write code that disables the button/exit until the boss room is cleared

**Comment by kepler471** [comment]
#### Couple ideas
1. We show a splash screen (just a single drawing/frame) of the Intern injecting some of the vaccine into the some infected moony surface or enemy, and would show your score next to it?

2. Another could be the Intern has an 'inject' animation/state. We zoom the camera in really close , they do the injection on the floor (whatever surface they are on, we can just disable movement when they have killed the enemies in the boss room. ) After the injection delete all the tiles other than background, and just watch the Intern fall for a second or two. Then transition to next level.

**Comment by kepler471** [comment]
Mother killed in boss room.

Mother death activates the lift.

#270
