### ISSUE TITLE
enhancement: Allow player to attach to wall backwards

### ISSUE THREAD

**Issue by kepler471** [kepler471/moonshot#83]
If wall jumping from one wall to another, and the user has not redirected the player towards that wall, we could allow player to still stick to that wall. This is similar to a bunch of other platformers, and makes jumping up chimneys/channels much smoother.

The argument against it is that in the current form there is a bit more skill required with getting the rhythmn of jump > redirect > jump > redirect etc...

Will try this after the other major player changes ( #66 #80 ), as I don't think it will take too much time to implement (famous last words).

**Comment by kepler471** [comment]
Maybe flipping the player is the solution to this issue. Flip could occur on landing on the wall, or when leaving the wall.

This would hopefully mean that if you land a wall-jump onto another wall, you will automatically attach to the wall, which would require less input, and improve flow. 

It is actually dependent on input type. M+KB vs controller, as doing all the movement work with your left hand on the keyboard is tricky. So maybe best to just add this system, makes it easy for that.

**Comment by wattsit** [comment]
Resloved with #164
